import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Misy",
  description: "Generated by create next app",
  authors: [{name:"Misy", url:"http://misy.dev"}]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="pt-26">{children}</main>
      </body>
    </html>
  );
}